### ISSUE TITLE
example : cannot load such file -- helix_runtime/native 

### ISSUE THREAD

**Issue by ZhangHanDong** [rustbridge/helix#7]
rust nightly 1.10.0

```shell
$ cd apps/helix/example/console
 cargo build
   Compiling libc v0.2.9
   Compiling libcruby-sys v0.1.0 (file:///vagrant_data/apps/helix/crates/libcruby-sys)
   Compiling cslice v0.1.0 (https://github.com/rustbridge/neon#f28e32c7)
   Compiling helix v0.1.0 (file:///vagrant_data/apps/helix)
   Compiling console v0.1.0 (file:///vagrant_data/apps/helix/examples/console)
note: link against the following native artifacts when linking against this static library
note: the order and any duplication can be significant on some platforms, and so may need to be preserved
note: library: dl
note: library: pthread
note: library: gcc_s
note: library: c
note: library: m
note: library: rt
note: library: util
```

```shell
helix/examples/console$   bundle exec rake irb
cargo build --release
gcc -Wl,-force_load,target/release/libconsole.a --shared -Wl,-undefined,dynamic_lookup -o lib/console/native.bundle
/vagrant_data/apps/helix/ruby/lib/helix_runtime.rb:2:in `require':LoadError: cannot load such file -- helix_runtime/native
```

**Comment by jwilm** [comment]
Which OS are you running? I see vagrant, so I'm going to assume this is some linux flavor. My experience on ubuntu 14.04 suggests that the gcc call to generate a shared library doesn't work correctly as it does on Darwin. Instead, I've had luck building a `dylib` directly with cargo on linux (which builds an .so without angering the linker).

**Comment by ZhangHanDong** [comment]
@jwilm thanks.

I  have rebuilded the helix_runtime gem, then it's ok. 

But I got the other error:

```ruby
~/apps/helix/examples/console$ bundle exec rake irb
cargo build --release
gcc -Wl,-force_load,target/release/libconsole.a --shared -Wl,-undefined,dynamic_lookup -o lib/console/native.bundle
/vagrant_data/apps/helix/examples/console/lib/console.rb:2:in `require':LoadError: cannot load such file -- console/native.bundle
irb(main):001:0> 

```

**Comment by jwilm** [comment]
Sounds like the same problem. I also found that `require 'libwhatever'` would fail for `.bundle` files on linux, but `.so` files were fine.

**Comment by aergonaut** [comment]
.bundle is the default shared library extension on Mac OS X. If you `require` a filename without an extension, Ruby tries looking for .rb, .so, .o and .dll files, and then also tries looking for the default shared library extension for the platform. Since that's .bundle on Mac OS X, creating lib/console/native.bundle works. The extension is different on other platforms though, so .bundle won't work elsewhere, like Linux.

**Comment by ZhangHanDong** [comment]
@aergonaut  
I complied it on my  vagrant with ubuntu box, I don't understand  why  there is the .bundle file.

**Comment by ZhangHanDong** [comment]
@aergonaut @jwilm 
Thanks, I see.

**Comment by aergonaut** [comment]
It's hard coded into the GCC call in the Rakefile

**Comment by ZhangHanDong** [comment]
@aergonaut yes, I see 😭

**Comment by jwilm** [comment]
@ZhangHanDong  you might have some luck building on linux by removing the gcc line from the Rakefile and switching the cargo crate-type to 'dylib'.

**Comment by ZhangHanDong** [comment]
@jwilm YesThat's what I did. 😄

**Comment by jwilm** [comment]
Oh, great! The sad emoji in your last post made me think otherwise :laughing:. Glad you got it working.

**Comment by ZhangHanDong** [comment]
@jwilm The sad emoji for the harded code!   😆
